# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/tri_ramp/tri_ramp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp || ORIG_REF_NAME==tri_ramp} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_0_0/tri_ramp_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_0_0 || ORIG_REF_NAME==tri_ramp_floating_point_0_0} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_0_1/tri_ramp_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_0_1 || ORIG_REF_NAME==tri_ramp_floating_point_0_1} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_1_0/tri_ramp_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_1_0 || ORIG_REF_NAME==tri_ramp_floating_point_1_0} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_1_1/tri_ramp_floating_point_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_1_1 || ORIG_REF_NAME==tri_ramp_floating_point_1_1} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_1_2/tri_ramp_floating_point_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_1_2 || ORIG_REF_NAME==tri_ramp_floating_point_1_2} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_3_0/tri_ramp_floating_point_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_3_0 || ORIG_REF_NAME==tri_ramp_floating_point_3_0} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_0_2/tri_ramp_floating_point_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_0_2 || ORIG_REF_NAME==tri_ramp_floating_point_0_2} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_1_3/tri_ramp_floating_point_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_1_3 || ORIG_REF_NAME==tri_ramp_floating_point_1_3} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_1_4/tri_ramp_floating_point_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_1_4 || ORIG_REF_NAME==tri_ramp_floating_point_1_4} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_7_0/tri_ramp_floating_point_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_7_0 || ORIG_REF_NAME==tri_ramp_floating_point_7_0} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_7_1/tri_ramp_floating_point_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_7_1 || ORIG_REF_NAME==tri_ramp_floating_point_7_1} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_floating_point_8_0/tri_ramp_floating_point_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_floating_point_8_0 || ORIG_REF_NAME==tri_ramp_floating_point_8_0} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_sub_0/tri_ramp_sub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_sub_0 || ORIG_REF_NAME==tri_ramp_sub_0} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_mul_0/tri_ramp_mul_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_mul_0 || ORIG_REF_NAME==tri_ramp_mul_0} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_mul_1/tri_ramp_mul_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_mul_1 || ORIG_REF_NAME==tri_ramp_mul_1} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_sout_0/tri_ramp_sout_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_sout_0 || ORIG_REF_NAME==tri_ramp_sout_0} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_sout_1/tri_ramp_sout_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_sout_1 || ORIG_REF_NAME==tri_ramp_sout_1} -quiet] -quiet

# IP: bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_ramp_clk_wiz_0 || ORIG_REF_NAME==tri_ramp_clk_wiz_0} -quiet] -quiet

# XDC: bd/tri_ramp/tri_ramp_ooc.xdc
