# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jlaw/ece544/sig_gen_ip/edit_sig_gen_v1_0.srcs/sources_1/bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0.xci
# IP: The module: 'tri_ramp_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jlaw/ece544/sig_gen_ip/edit_sig_gen_v1_0.srcs/sources_1/bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_ramp_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlaw/ece544/sig_gen_ip/edit_sig_gen_v1_0.srcs/sources_1/bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_ramp_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlaw/ece544/sig_gen_ip/edit_sig_gen_v1_0.srcs/sources_1/bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_ramp_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/jlaw/ece544/sig_gen_ip/edit_sig_gen_v1_0.srcs/sources_1/bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0.xci
# IP: The module: 'tri_ramp_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jlaw/ece544/sig_gen_ip/edit_sig_gen_v1_0.srcs/sources_1/bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_ramp_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlaw/ece544/sig_gen_ip/edit_sig_gen_v1_0.srcs/sources_1/bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_ramp_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jlaw/ece544/sig_gen_ip/edit_sig_gen_v1_0.srcs/sources_1/bd/tri_ramp/ip/tri_ramp_clk_wiz_0/tri_ramp_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_ramp_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
